import rooms from '../constants/rooms';

export const roomsArray = [
  {
    id: 1,
    show: true,
    titleKey: 'rooms.jacuzzi.title',
    shortDescriptionKey: 'rooms.jacuzzi.short',
    longDescriptionKey: 'rooms.jacuzzi.long',
    longDescriptionMoreKey: 'rooms.jacuzzi.long_more',
    slug: 'spa-bath-apartment',
    headerImg: rooms.jacuzzi,
    room_nums: [],
  },
  {
    id: 2,
    show: true,
    titleKey: 'rooms.standard_room.title',
    shortDescriptionKey: 'rooms.standard_room.short',
    longDescriptionKey: 'rooms.standard_room.long',
    longDescriptionMoreKey: 'rooms.standard_room.long_more',
    slug: 'standard-room',
    headerImg: rooms.standard_room,
    room_nums: ['1a', '2a', '14'],
  },
  {
    id: 3,
    show: true,
    titleKey: 'rooms.deluxe_room.title',
    shortDescriptionKey: 'rooms.deluxe_room.short',
    longDescriptionKey: 'rooms.deluxe_room.long',
    longDescriptionMoreKey: 'rooms.deluxe_room.long_more',
    slug: 'deluxe-room',
    headerImg: rooms.deluxe_room,
    room_nums: ['2', '5', '8', '11'],
  },
  {
    id: 4,
    show: true,
    titleKey: 'rooms.deluxe_studio.title',
    shortDescriptionKey: 'rooms.deluxe_studio.short',
    longDescriptionKey: 'rooms.deluxe_studio.long',
    longDescriptionMoreKey: 'rooms.deluxe_studio.long_more',
    slug: 'deluxe-studio-apartment',
    headerImg: rooms.deluxe_studio,
    room_nums: ['6'],
  },
  {
    id: 5,
    show: false,
    titleKey: 'rooms.standard_apt.title',
    shortDescriptionKey: 'rooms.standard_apt.short',
    longDescriptionKey: 'rooms.standard_apt.long',
    longDescriptionMoreKey: 'rooms.standard_apt.long_more',
    slug: 'standard-apartment',
    headerImg: '',
    room_nums: ['7'],
  },
  {
    id: 6,
    show: true,
    titleKey: 'rooms.triple_apt.title',
    shortDescriptionKey: 'rooms.triple_apt.short',
    longDescriptionKey: 'rooms.triple_apt.long',
    longDescriptionMoreKey: 'rooms.triple_apt.long_more',
    slug: 'triple-studio-apartment',
    headerImg: rooms.triple_apt,
    room_nums: ['12'],
  },
  {
    id: 7,
    show: true,
    titleKey: 'rooms.standard_studio_apt.title',
    shortDescriptionKey: 'rooms.standard_studio_apt.short',
    longDescriptionKey: 'rooms.standard_studio_apt.long',
    longDescriptionMoreKey: 'rooms.standard_studio_apt.long_more',
    slug: 'standard-studio-apartment',
    headerImg: rooms.standard_studio_apt,
    room_nums: ['13', '16'],
  },
  {
    id: 8,
    show: true,
    titleKey: 'rooms.deluxe_family.title',
    shortDescriptionKey: 'rooms.deluxe_family.short',
    longDescriptionKey: 'rooms.deluxe_family.long',
    longDescriptionMoreKey: 'rooms.deluxe_family.long_more',
    slug: 'deluxe-family-apartment',
    headerImg: rooms.deluxe_family,
    room_nums: ['3', '4', '9', '10'],
  },
];
